- hosts: all
  become: true

  vars:
    packages:
      - git
      - zlib-devel
      - curl-devel
      - mysql-devel

    php_packages:
      - php70
      - php70-devel
      - php70-cli
      - php70-common
      - php70-mbstring
      - php70-gd
      - php70-gmp
      - php70-mcrypt
      - php70-xml
      - php70-imap
      - php70-intl
      - php70-mysqlnd
      - php70-pdo
      - php70-opcache
    php_ini_replacements:
      - regexp: 'expose_php *= *On'
        replace: 'expose_php = Off'
      - regexp: 'post_max_size *= *8M'
        replace: 'post_max_size = 16M'

  tasks:
  - name: set timezone to Asia/Tokyo
    timezone:
      name: Asia/Tokyo

  - name: install packages
    yum: name={{ item }} state=installed
    with_items: "{{ packages }}"

  - name: install php packages
    yum: name={{ item }} state=installed
    with_items: "{{ php_packages }}"

  - name: edit php.ini
    replace:
      dest: /etc/php.ini
      backup: yes
      regexp: '{{ item.regexp}}'
      replace: '{{ item.replace }}'
    with_items: "{{ php_ini_replacements }}"

  - include: tasks/php-wpcli.yml
  - include: tasks/php-composer.yml

  - name: copy httpd.conf
    copy:
      src: etc/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
    notify: httpd restart

  - name: enable httpd service
    service:
      name: httpd
      enabled: yes
      state: started

  handlers:
    - name: httpd restart
      service:
        name: httpd
        state: restarted
